# Workflow to update my recent GitHub activity in public repos

name: github-activity
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    name: Update README with my most recent GitHub activity in public repos
    steps:
      - uses: actions/checkout@v2
      - uses: Readme-Workflows/recent-activity@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          CONFIG_FILE: "workflow_settings.yml"
